workflows:
  ios-build:
    name: Build iOS IPA
    environment:
      xcode: latest
      vars:
        XCODE_WORKSPACE: "eSchool.xcworkspace"
        XCODE_SCHEME: "Samanalae School"
        EXPORT_OPTIONS_PLIST: "ExportOptions.plist"
    scripts:
      - name: Install CocoaPods
        script: |
          gem install cocoapods
          pod install --repo-update
      - name: Build archive
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/ios_archive.xcarchive \
            archive
      - name: Export .ipa
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_archive.xcarchive \
            -exportPath $CM_BUILD_DIR \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST"
    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/*.xcarchive
